import = [ "~/.config/alacritty/themes/themes/gnome_terminal.toml" ]
[env]
TERM = "xterm-256color"
[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[window]
padding.x = 10
padding.y = 10
blur = true
decorations = "Buttonless"

