[env]
TERM = "xterm-256color"
[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18


[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
blur = true
decorations = "Buttonless"
opacity = 0.8

[keyboard]
bindings = [
  { key = "B", mods = "Control", mode = "~Search", action = "ToggleViMode" },
]

[general]
import = ["~/.config/alacritty/themes/themes/gnome_terminal.toml"]
